### ISSUE TITLE
checklist MVP

### ISSUE THREAD

**Issue by Romanior** [BookingSync/calendar-widget#6]
### First beta
- [x] translations support
- [x] custom start of the week, based on locale and on parameter (e.g. en-US has Sunday)
- [x] Basic events
calendar:loading
calendar:loaded
dates:checkin:change
dates:checkout:change
dates:clear (listener)

- [x] month arrows
- [x] rental selector if more then one rental specified in parameters
- [x] ability to reset selected range
- [x] nightly rates display directly in cells or on tooltip (parameters)

### MVP

- [x] responsive layout, IE9 flexbox fallback
- [ ] show selected dates and nights. e.g. "12/12/2016 - 14/12/216, 3 days/2 nights"

### NON-MVP
- [ ] month selector drop-down (January 2017/February 2017...)
- [ ] En-Gb, en-Us, fr support locale formats (currency?)
- [x]  Minimum stay based on map, not static parameter.
- [ ] CSS Animated transitions
- [x] More events, specify please
- [ ] Show week number
